# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='license',
            field=models.IntegerField(default=1, verbose_name=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='license_author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='status',
            field=models.IntegerField(default=1, verbose_name=1),
            preserve_default=False,
        ),
    ]
