# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('emailatleta', models.EmailField(max_length=50, verbose_name='Email')),
                ('datainicio', models.DateField(verbose_name='Data de inicio')),
                ('datanascimento', models.DateField(verbose_name='Data de nascimento')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('cc', models.CharField(max_length=12, verbose_name='Cartão do Cidadão')),
                ('nif', models.IntegerField(verbose_name='Número de Identifacação Fiscal')),
                ('telefone', models.CharField(max_length=9, verbose_name='Nº Telefone')),
                ('telefone2', models.CharField(max_length=9, verbose_name='Nº Telefone urgência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Inscrição Atleta',
                'verbose_name_plural': 'Inscrições Atletas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='PlanoMensalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do plano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor €')),
                ('horario', models.CharField(max_length=20, verbose_name='Horário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Plano e mensalidade',
                'verbose_name_plural': 'Planos e mensalidade',
                'ordering': ('valor',),
            },
        ),
        migrations.CreateModel(
            name='SaudeAnamnese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest01', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Doença cardiovascular ou pulmonar (asma, bronquite, etc.)')),
                ('quest02', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Doença metabólica (tiroide, renal ou hepática)')),
                ('quest03', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Diabetes tipo I ou II')),
                ('quest04', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Dor ou desconforto no peito em repouso ou exercício')),
                ('quest05', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Desmaios, tonturas ou perda de consciência')),
                ('quest06', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Dificuldades em respirar ou problemas respiratórios repentinos durante a noite')),
                ('quest07', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Palpitações ou taquicardia')),
                ('quest08', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Dor severa nas pernas durante a marcha')),
                ('quest09', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Tensão arterial maior que 140/90 mm Hg ou sob medicação')),
                ('quest010', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Edema no tornozelo')),
                ('quest011', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Colesterol Total maior que 240 mg/dl ou sob medicação')),
                ('quest012', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='História familiar de enfarte do miocárdio ou morte súbita do pai/mãe ou outro familiar em primeiro grau antes dos 55/65 anos')),
                ('quest013', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Índice de Massa Corporal maior que 30 (kg/m2)')),
                ('quest014', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Fumador ou que tenha deixado de fumar nos últimos 6 meses')),
                ('quest015', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Sem programa de exercício regular há mais de 6 meses')),
                ('quest016', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Algum problema de saúde não mencionado e/ou qualquer outro fator condicionante do programa de exercício físico a elaborar?')),
                ('quest017', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Doença recente?')),
                ('quest018', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Hospitalização?')),
                ('quest019', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Procedimentos cirúrgicos?')),
                ('quest020', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Pratica algum tipo de exercício regularmente fora do KC?')),
                ('quest021', models.TextField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Se sim, qual e quantas vezes por semana?')),
                ('quest022', models.TextField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Alguma observação importante a declarar?')),
                ('quest023', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Declara que compreendeu integralmente o conteúdo deste documento?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Questionário de Saúde e Anamnese Desportiva',
                'verbose_name_plural': 'Questionário de Saúde e Anamnese Desportiva',
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='atleta',
            name='planomensalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlanoMensalidade', verbose_name='Planos e mensalidade'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='saudeanamnese',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SaudeAnamnese', verbose_name='Questionário de Saúde e Anamnese Desportiva'),
        ),
    ]
