# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroatleta', models.IntegerField(verbose_name='Nº do Atleta')),
                ('datapresenca', models.DateField(blank=True, verbose_name='Data da presença')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name_plural': 'Presenças',
                'verbose_name': 'Presença',
                'ordering': ('datapresenca',),
            },
        ),
        migrations.AlterField(
            model_name='atleta',
            name='saudeanamnese',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.SaudeAnamnese', verbose_name='Questionário de Saúde e Anamnese Desportiva'),
        ),
    ]
