# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peso')),
                ('metbasal', models.CharField(max_length=5, verbose_name='Met. basal')),
                ('idadebiologica', models.IntegerField(verbose_name='Idade biológica')),
                ('agua', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Água')),
                ('gorduraviceral', models.CharField(max_length=5, verbose_name='Gordura visceral')),
                ('massaossea', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Massa ossea')),
                ('massamuscular', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Massa muscular total')),
                ('massagorda', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Massa gorda total')),
                ('pescoco', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pescoço')),
                ('ombros', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ombros')),
                ('peitos', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peitos')),
                ('cintura', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cintura')),
                ('abdominal', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Abdominal')),
                ('quadril', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Quadril')),
                ('coxaproximal', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Coxa proximal')),
                ('coxamedial', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Coxa medial')),
                ('dataavaliacao', models.DateField(verbose_name='Data da avaliação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Avaliado em')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Atleta', verbose_name='Nº do atleta')),
            ],
            options={
                'verbose_name_plural': 'Avalizações',
                'verbose_name': 'Avaliação',
                'ordering': ('created_at',),
            },
        ),
    ]
