# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ('atleta__nome',), 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='saudeanamnese',
            options={'ordering': ('atleta__nome',), 'verbose_name': 'Questionário de Saúde e Anamnese Desportiva', 'verbose_name_plural': 'Questionário de Saúde e Anamnese Desportiva'},
        ),
        migrations.AddField(
            model_name='atleta',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='abdominal',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Abdominal cm'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='agua',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Água %'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='cintura',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cintura cm'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='coxamedial',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Coxa medial cm'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='coxaproximal',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Coxa proximal cm'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='gorduraviceral',
            field=models.CharField(max_length=5, verbose_name='Gordura visceral nível'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='idadebiologica',
            field=models.IntegerField(verbose_name='Idade biológica anos'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='massagorda',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Massa gorda total %'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='massamuscular',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Massa muscular total kg'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='massaossea',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Massa ossea kg'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='metbasal',
            field=models.CharField(max_length=5, verbose_name='Met. basal Kcal'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='ombros',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ombros cm'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='peitos',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peitos cm'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pescoco',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pescoço cm'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peso Kg'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='quadril',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Quadril cm'),
        ),
    ]
