# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160309_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saudeanamnese',
            old_name='id_atleta',
            new_name='atleta',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='id_saudeanamnese',
        ),
    ]
