# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_presenca_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='planomensalidade',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo'),
        ),
    ]
