# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('nome',), 'verbose_name': 'Inscrição Atleta', 'verbose_name_plural': 'Inscrições Atletas'},
        ),
    ]
