# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoMensalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do plano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor €')),
                ('horario', models.CharField(max_length=20, verbose_name='Horário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ativo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Plano e mensalidade',
                'verbose_name_plural': 'Planos e mensalidade',
                'ordering': ('valor',),
            },
        ),
    ]
